services:
  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: db_systemgym
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: systemgym
      MYSQL_PASSWORD: Ca!@#90712321#!
    ports:
      - "3307:3306"